### DISCUSSION TITLE
Source as a Sensor

### DISCUSSION THREAD

**Discussion by STGMavrick** [mvdwetering/yamaha_ynca#111] [General]
Hi - is it possible to have the current source as a sensor? I noticed that when you look at the properties of the "Main" entity it actively reflects the current input on the receiver. While that window is open I can change the input via the IR remote and that "Source" section automatically changes to the mode I set via the remote. It also automatically knows the name of each source set in the receiver as well. I'd like to add an automation to change lights based on source selection read from the receiver.
![image](https://user-images.githubusercontent.com/26092482/211111277-6c678a11-d5f5-4baf-a6f2-6f592690dd5c.png)

**Comment by mvdwetering** [comment]
You can already do automations on source changes.

As an example this automation toggles a light when the source changes to "Shield".
I built it with the UI, but I had to manually type "source" in the Attribute textbox, the rest was selectable from dropdowns. I copied the resulting YAML below, so it should be able to paste this in a new automation and switch back to UI it that is what you prefer.

```
alias: Toggle light when source changes to Shield
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.main
    attribute: source
    to: Shield
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.hue_aurelle_panel_rechts
mode: single
```
