### DISCUSSION TITLE
Configure Additional Buttons

### DISCUSSION THREAD

**Discussion by ChristophCaina** [mvdwetering/yamaha_ynca#146] [Q&A]
Hey :)
I've just found this integration - and by default, it does provide some buttons for the following actions:

- BlueRay / DVD
- TV
- Radio
and so on...

I would also like to add "custom" buttons for selecting a specific Input Source (HMI1, HDMI2, HDMI3, and so on...) Unfortunately, these are only visible within the MediaPlayer Card itself...

Now, I would like to know, how to create scenes that I can then use as buttons... unfortunately, I can only see the following scene:
![image](https://user-images.githubusercontent.com/26391061/223067689-36e40edf-afe0-4ba4-90c0-6186b8b06d52.png)
and I have no Idea on how to switch the input source here...

**Comment by mvdwetering** [comment]
The "BluRay / DVD" and other buttons are exposing the scenes as they are available on your receiver (the 4 buttons on the front). You can change what they do, but I don't recall how, please check the manual of your receiver on how that works,

If you just want to have extra buttons (as in not provided by the integration) then you  can just add a button card to the frontend. And call the generic `media_player.select_source` service. Something like the card below should work.

```yaml
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: media_player.select_source
  data:
    source: XBox
  target:
    entity_id: media_player.main
icon: mdi:microsoft-xbox-controller
name: Select XBox input
```

BTW the `yamaha_ynca.send_raw_ynca` is only intended for debugging. You probably will never need it. Typically you can use the generic Home Assistant services.
