### DISCUSSION TITLE
Sensor active input

### DISCUSSION THREAD

**Discussion by wadling** [mvdwetering/yamaha_ynca#289] [Ideas]
Would be nice to be able to determine which input that is active, ie hdmi1, aux, xlr, phono etc.

A couple example use cases
You could enable vinyl automation when phono have been active for a certain amount of time
A movie automation that closes the curtains if it is too bright, triggered by the hdmi connected to bluray being active.
A diy hdmi cec alternative. Now I have home assistant set to turn on my tv and yamaha avr with the right scene. It is triggered by the chromecast switching status to active. (Hdmi cec worked fine for a couple of years for me, but since I got a cwgtv it only works for a short while)

**Comment by mvdwetering** [comment]
It is already possible to put conditions on which source is active with the available mediaplayer entity. See screenshot/yaml below. 

A few things to note.
* The source is only available when the media_player is on. Due to all the different possible states (off/idle/playing/paused/etc...) it is generally easier to check if the media_player is "not off"
* When selecting to create a condition you need to select "Entity" instead of "Device". The Device conditions don't offer checking for source (this would be a nice feature request for Home Asssistant)

![image](https://github.com/mvdwetering/yamaha_ynca/assets/732514/9de2582d-a1ea-46c2-9049-2ca20cacceb9)

Or in yaml.
```
description: "Just a test automation"
mode: single
trigger: []
condition:
  - condition: state
    entity_id: media_player.rx_a810_main
    attribute: source
    state: Shield
action: []

```
