### DISCUSSION TITLE
RX-A4A how to enable/disable SURROUND:AI?

### DISCUSSION THREAD

**Discussion by smallghost** [mvdwetering/yamaha_ynca#399] [General]
Is there any method to turn on/off SURROUND:AI?
SURROUND:AI is not in the sound mode list.
I tried sending a raw YNCA command, but it didn't work. (`@MAIN:PGEQ=AI` / `@MAIN:PGEQ=OFF`) returns an undefined message.
Am I using the wrong function?

**Comment by mvdwetering** [comment]
I don't know what `PGEQ` is or does. Never heard of it. I could also not find anything with Google.
Where did you find that it would control Surround:AI setting? 

The usual way to figure out which command to use is to change the setting to all possible states. Then after that download diagnostics and look for possible candidates. You can download the diagnostics from the menu on the integration page. If you attach the diagnostics file here I can have a look.

![image](https://github.com/user-attachments/assets/b1a6ebeb-a4d6-4634-aade-791ec33cb4a2)


(fyi I deleted the other discussion which seemed a duplicate of this one)

**Reply by smallghost** [reply]
Thanks for you help, after i download diagnostics, i saw the surround ai commend, I try to send raw data and it's working. Thank you again.

developer tool
```
action: yamaha_ynca.send_raw_ynca
data:
  raw_data: " @MAIN:SURROUNDAI=On"
target:
  entity_id: media_player.rx_a4a_main
```

scripts.yaml
```
turn_on_surround_ai:
  alias: "開啟 Surround:AI"
  sequence:
    - service: yamaha_ynca.send_raw_ynca
      data:
        entity_id: media_player.rx_a4a_main
        raw_data: "@MAIN:SURROUNDAI=On"
```

BTW, PGEQ is come from chatgpt, haha.....
