### ISSUE TITLE
service.mediaplayer.select_source does not change the source port ...

### ISSUE THREAD

**Issue by ChristophCaina** [mvdwetering/yamaha_ynca#148]
**Describe the bug**

I've tried to change the source on my AV Receiver (Change between the different HDMI Ports)...
Only HDMI1 seems to work.

HDMI 1 is called "SetTopBox"... the AV Recveiver is successfully switching to that port when I use the Service Select_source.
Any other port did not work:

not working yaml service:
```
service: media_player.select_source
data:
  source: HDMI4
target:
  entity_id: media_player.rx_v477
```

After some further analyzis, is seems to be related with the names of the ports.
As you can see in the below output from the debug json, the Port names contains spaces in front and after the name.

```
        "Received: @SYS:INPNAMEHDMI1=SetTopBox",
        "Received: @SYS:INPNAMEHDMI2= Blu-ray ",
        "Received: @SYS:INPNAMEHDMI3=   MD    ",
        "Received: @SYS:INPNAMEHDMI4=  HDMI4  ",
        "Received: @SYS:INPNAMEHDMI5=  HDMI5  ",
        "Received: @SYS:INPNAMEHDMI6=  HDMI6  ",
        "Received: @SYS:INPNAMEAV1=   AV1   ",
        "Received: @SYS:INPNAMEAV2=   AV2   ",
        "Received: @SYS:INPNAMEAV3=   AV3   ",
        "Received: @SYS:INPNAMEAV4=   AV4   ",
        "Received: @SYS:INPNAMEAV5=   AV5   ",
        "Received: @SYS:INPNAMEAV6=   AV6   ",
        "Received: @SYS:INPNAMEUSB=   USB   ",
```

These spaces needs to be reflected in the Service Call:
```
service: media_player.select_source
data:
  source: "  HDMI4  "
target:
  entity_id: media_player.rx_v477
```
is working as expected.

**To Reproduce**

**Expected behavior**

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.

**Home Assistant version information:**
 - Version [e.g. 2022.8.0]

**Additional context**
