### ISSUE TITLE
Unable to save or load presets on RX-V673

### ISSUE THREAD

**Issue by egaldg** [mvdwetering/yamaha_ynca#379]
**Describe the bug**
Unable to save or load preset on RX-V673

The RX-V673 was playing a net radio post.
Using the following script i tried to save presets:

```yaml
sequence:
  - action: yamaha_ynca.store_preset
    data:
      preset_id: 1
    target:
      entity_id: media_player.rx_v673_main
alias: Yamaha save preset 1
```

When selecting net radio reset 1 through the media player, nothing happens.
I've tried different preset numbers, always fails to work.

I also tried setting the preset using the following script:
```yaml
sequence:
  - action: media_player.play_media
    data:
      media_content_id: netradio:preset:1
      media_content_type: music
    target:
      entity_id: media_player.rx_v673_main
alias: select preset 1
```
But once again nothing happens.

Versions:
Core 2025.1.4
Supervisor 2024.12.3
Operating System 14.2
Frontend 20250109.2

Yamaha (YNCA) 7.14.0
